feat: SynchronizeGithubUserContributions
DSCHUFS/Jandi-BE pull request #2
Opened 2024-01-10 04:43 UTC by g00hyun

2024-01-10 15:16 UTC, gomsang approved these changes
날짜 부분만 다시 확인 부탁드리겠습니다!

2024-01-10 15:16 UTC, gomsang commented on functions/src/service/ContributionService.ts
> +        const lastDate = new Date(startDate);
trackingBeginDate 를 기준으로 28일이면, lastDate 가 trackingBeginDate + 27 이어야 할것 같은데 확인 부탁드릴게요!

2024-01-10 15:35 UTC, gomsang requested changes

2024-01-10 15:35 UTC, gomsang commented on functions/src/controller/github/GithubController.ts
>          const currentDate = new Date();
currentDate 가 아무래도 GMT 인것 같아서 한국 시간으로 00시가 되었을때에도 contributions 배열이 증가되지 않는 문제가 되어 있습니다.

시간 조정 하여 GMT+9로 만들어야 할거 같아요.

2024-01-11 01:16 UTC, g00hyun commented on functions/src/service/ContributionService.ts
> +        const lastDate = new Date(startDate);
line17에 보면 lastdate에 +27해 준 코드가 있습니다

2024-01-11 01:50 UTC, g00hyun commented on functions/src/controller/github/GithubController.ts
>          const currentDate = new Date();
수정해서 올렸습니다.
확인 부탁드려요

2024-01-11 01:52 UTC, merged

2024-01-11 01:53 UTC, gomsang reviewed
수고하셨습니다!